### ISSUE TITLE
Identify practices for handling errors

### ISSUE THREAD

**Issue by adityasharma7** [hotwax/oms-api#40]
## What is the motivation for adding/enhancing this feature?

Possible ways we could think of handling errors:

1. Throw an error, passing details of the server error in a defined format. In app specific code, we could handle success in then() and error in the catch(). The developer may choose to go with the async await pattern too. This behavior is more close to how API calls behave, so more preferred.
2. Instead of throwing errors, a single response object for both cases with certain attributes that helps identifying the error. Helps to skip having catch blocks everwhere, handling the error centralised in package and asserting success/failure based upon the defined attributes in response
 

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by ymaheshwari1** [comment]
In the current implementation for oms-api, we are following the second way for error handling. We have defined a pattern for error response containing following properties: 
```js
code
message
serverResponse
```
On the application side, whenever calling the oms-api we are checking whether the response from oms-api contains an `error code` and then handling the case. So in this case, the oms-api is always returning a resolved promise even in case of errors.

In first approach, in case of error from the server, the oms-api will return a rejected promise in the format containing a user-friendly message, and the error message from server, if needed on frontend for debugging. In this way, on application side the developer does not have to make an extra check for `error code` in the oms-api response, and simply by using try/catch error handling can be done.

We have concluded that we will go ahead by using the second approach defined, so that the errors can be simply handled on front-end side.
